import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { getCart } from '../../api/cartApi.js';
import { placeOrder } from '../../api/orderApi.js';
import { listAddresses } from '../../api/userApi.js';
import Navbar from '../../components/common/Navbar.jsx';
import PriceSummary from '../../components/cart/PriceSummary.jsx';

const addressText=a=>[a.line1,a.city,a.state,a.pincode].filter(Boolean).join(', ');
export default function CheckoutPage(){
 const nav=useNavigate(), coupon=useLocation().state?.coupon||'';
 const [addrs,setAddrs]=useState([]),[sel,setSel]=useState(null),[pay,setPay]=useState('COD'),[cart,setCart]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 const load=()=>listAddresses().then(l=>{setAddrs(l);const stored=localStorage.getItem('tidemart_addr');const chosen=l.find(a=>String(a.id)===stored)||l.find(a=>a.isDefault)||l[0];if(chosen){setSel(chosen.id);localStorage.setItem('tidemart_addr',String(chosen.id));localStorage.setItem('tidemart_pin',chosen.pincode)}});
 useEffect(()=>{load()},[]); useEffect(()=>{getCart(coupon,pay).then(setCart).catch(()=>{})},[pay,coupon]);
 const choose=a=>{setSel(a.id);localStorage.setItem('tidemart_addr',String(a.id));localStorage.setItem('tidemart_pin',a.pincode);window.dispatchEvent(new CustomEvent('tidemart-location',{detail:{addressId:String(a.id),pincode:a.pincode}}));};
 const place=async()=>{setErr('');if(!sel)return setErr('Choose a delivery address');setBusy(true);try{const o=await placeOrder({addressId:sel,paymentMethod:pay,coupon,demoPaymentOk:true});nav(`/orders/${o.id}`)}catch(e){setErr(e.response?.data?.message||'Could not place order')}finally{setBusy(false)}};
 return <><Navbar/><main className="max-w-5xl mx-auto p-4 lg:p-6"><div className="grid lg:grid-cols-[1fr_360px] gap-6"><div><h1 className="text-2xl font-bold mb-4">Checkout</h1><section className="bg-white border rounded-2xl p-4 mb-4"><div className="flex justify-between items-center mb-3"><h2 className="font-bold">Delivery address</h2><Link to="/addresses" className="text-brand text-sm font-semibold">Manage addresses</Link></div>{!addrs.length?<p className="text-sm text-slate-500">No saved address. <Link className="text-brand font-semibold" to="/addresses">Add one</Link>.</p>:addrs.map(a=><label key={a.id} className={`flex gap-3 border rounded-xl p-4 mb-2 cursor-pointer ${sel===a.id?'border-brand bg-brand/5':'border-slate-200'}`}><input type="radio" className="mt-1" checked={sel===a.id} onChange={()=>choose(a)}/><span className="text-sm"><b>{a.name}</b>{a.isDefault&&<span className="ml-2 text-xs text-brand font-bold">DEFAULT</span>}<br/>{addressText(a)}<br/><span className="text-slate-500">{a.phone}</span></span></label>)}</section><section className="bg-white border rounded-2xl p-4"><h2 className="font-bold mb-3">Payment</h2>{[['UPI','UPI'],['CARD','Card'],['COD','Cash on delivery'],['WALLET','TideMart Wallet']].map(([k,l])=><label key={k} className={`flex items-center gap-3 border rounded-xl p-3 mb-2 cursor-pointer ${pay===k?'border-brand bg-brand/5':''}`}><input type="radio" checked={pay===k} onChange={()=>setPay(k)}/><span className="font-medium">{l}</span></label>)}</section></div><aside className="bg-white border rounded-2xl p-4 h-fit lg:sticky lg:top-24"><h2 className="font-bold mb-3">Order summary</h2>{cart?.items?.map(i=><div key={i.itemId} className="flex gap-3 py-3 border-b"><img src={i.imageUrl} className="w-16 h-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><Link to={`/product/${i.productId}`} className="text-sm font-semibold line-clamp-2">{i.name}</Link><p className="text-xs text-slate-500 mt-1">Size {i.size} · Qty {i.qty}</p><p className="text-xs text-slate-500">Sold by {i.sellerName}</p></div><b className="text-sm">₹{Math.round(i.price*i.qty)}</b></div>)}<PriceSummary price={cart?.price}/>{err&&<p className="text-red-600 text-sm mt-3">{err}</p>}<button disabled={busy||!sel||!cart?.items?.length} onClick={place} className="w-full mt-4 bg-brand-accent text-white py-3 rounded-xl font-bold disabled:opacity-50">{busy?'Placing order...':'Place order'}</button><p className="text-xs text-slate-400 mt-3">UPI and card are demo payments. No real money is charged.</p></aside></div></main></>
}
