import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { PHOTO_ASSETS } from '../../data/photoAssets.js';
const FALLBACK_BANNERS=[
 {imageUrl:PHOTO_ASSETS.campaign,title:'Fresh looks. Happy prices.',subtitle:'Ethnic wear • Dresses • Jewellery • Footwear',link:'/search?q=women'},
 {imageUrl:PHOTO_ASSETS.home,title:'Refresh your home.',subtitle:'Useful picks for every room and routine.',link:'/search?q=home'},
 {imageUrl:PHOTO_ASSETS.footwear,title:'Style that moves with you.',subtitle:'Everyday footwear at easy prices.',link:'/search?q=footwear'},
 {imageUrl:PHOTO_ASSETS.beauty,title:'Glow for less.',subtitle:'Beauty, skincare and self-care picks.',link:'/search?q=beauty'},
];
export default function BannerCarousel({banners=[]}){const slides=(banners?.length && banners)||FALLBACK_BANNERS;const [active,setActive]=useState(0);useEffect(()=>setActive(0),[slides.length]);useEffect(()=>{if(slides.length<2)return;const id=setInterval(()=>setActive(x=>(x+1)%slides.length),5000);return()=>clearInterval(id)},[slides.length]);const x=slides[active]||slides[0];return <section className="max-w-7xl mx-auto px-4 lg:px-6 pt-5"><div className="relative overflow-hidden rounded-2xl shadow-sm border border-slate-100 bg-slate-200"><Link to={x.link||'/search'} className="block relative"><img src={x.imageUrl} alt={x.title||'TideMart offer'} className="w-full aspect-[3.1/1] min-h-[190px] object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950/65 via-slate-950/20 to-transparent"/><div className="absolute inset-y-0 left-0 flex items-center p-6 md:p-10 max-w-xl text-white"><div><p className="text-xs uppercase tracking-[.22em] font-bold opacity-90">TideMart picks</p><h2 className="text-2xl md:text-4xl font-black mt-2 leading-tight">{x.title}</h2><p className="mt-2 text-sm md:text-base opacity-90">{x.subtitle}</p><span className="inline-block mt-4 bg-white text-slate-900 rounded-lg px-4 py-2 text-sm font-bold">Shop now</span></div></div></Link>{slides.length>1&&<div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-1.5">{slides.map((_,i)=><button key={i} aria-label={`Go to banner ${i+1}`} onClick={()=>setActive(i)} className={`h-1.5 rounded-full transition-all ${i===active?'w-7 bg-white':'w-1.5 bg-white/60'}`}/>)}</div>}</div></section>;}
